### ISSUE TITLE
[sapphire] Error when calling bind on Windows

### ISSUE THREAD

**Issue by tysmith** [MozillaSecurity/grizzly#100]
```
Traceback (most recent call last):
  File "grizzly\reduce\reduce.py", line 452, in run
    result = reducer.run()
  File "c:\users\user\code\fuzzmanager\lithium\src\lithium\reducer.py", line 1312, in run
    result = self.strategy.main(self.testcase, self.interesting, self.testcaseTempFilename)
  File "c:\users\user\code\fuzzmanager\lithium\src\lithium\reducer.py", line 378, in main
    result, anySingle, testcase = self.run(testcase, interesting, tempFilename)  # pylint: disable=invalid-name
  File "c:\users\user\code\fuzzmanager\lithium\src\lithium\reducer.py", line 454, in run
    if interesting(test_to_try):
  File "c:\users\user\code\fuzzmanager\lithium\src\lithium\reducer.py", line 1469, in interesting
    inter = self.conditionScript.interesting(self.conditionArgs, tempPrefix)
  File "grizzly\reduce\interesting.py", line 254, in interesting
    if self._run(testcase, run_prefix):
  File "grizzly\reduce\interesting.py", line 305, in _run
    self.server = sapphire.Sapphire()
  File "sapphire\core.py", line 221, in __init__
    self._socket = Sapphire._create_listening_socket(allow_remote, port)
  File "sapphire\core.py", line 270, in _create_listening_socket
    sock.bind(("0.0.0.0" if allow_remote else "127.0.0.1", port))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions
```

**Comment by tysmith** [comment]
Should be fixed by commit 60cfa227
