### ISSUE TITLE
failed to running 'no-op' example adapter

### ISSUE THREAD

**Issue by areuu** [MozillaSecurity/grizzly#154]
I am following the wiki to running grizzly, but ... it gives me a error

```
➜  grizzly python -m grizzly ../browsers/firefox/firefox no-op -p ../prefs.js 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/uuu/browser_fuzzing/grizzly/grizzly/__main__.py", line 9, in <module>
    from .adapters import load
  File "grizzly/adapters/__init__.py", line 7, in <module>
    from grizzly.common import Adapter
  File "grizzly/common/__init__.py", line 6, in <module>
    from .adapter import Adapter, AdapterError
  File "grizzly/common/adapter.py", line 18
    class Adapter(metaclass=abc.ABCMeta):
                           ^
SyntaxError: invalid syntax
➜  grizzly 
```

**Comment by pyoor** [comment]
@areuu Grizzly requires python 3.  We should probably throw on any attempt to use it with python < 3.5.

**Comment by tysmith** [comment]
@areuu Thanks for letting us know. As @pyoor metioned Grizzly requires Python3 (Python2 is [EOL](https://www.python.org/doc/sunset-python-2/).) I have made a few updates to the wiki to help point this out.

If this does not resolve the issue feel free to reopen.
