### ISSUE TITLE
[replay] TypeError: 'NoneType' object is not iterable when replaying zip file

### ISSUE THREAD

**Issue by pyoor** [MozillaSecurity/grizzly#161]
Unhandled exception when trying to replay a testcase using the testcase archive (zip).

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/forb1dden/tools/grizzly/grizzly/replay/__main__.py", line 11, in <module>
    sysexit(ReplayManager.main(ReplayArgs().parse_args()))
  File "/home/forb1dden/tools/grizzly/grizzly/replay/replay.py", line 420, in main
    replay.testcases if args.include_test else None)
  File "/home/forb1dden/tools/grizzly/grizzly/replay/replay.py", line 174, in report_to_filesystem
    reporter.submit(tests, report=report)
  File "/home/forb1dden/tools/grizzly/grizzly/common/reporter.py", line 331, in submit
    self._submit_report(report, test_cases)
  File "/home/forb1dden/tools/grizzly/grizzly/common/reporter.py", line 359, in _submit_report
    for test_number, test_case in enumerate(test_cases):
TypeError: 'NoneType' object is not iterable
```

**Comment by tysmith** [comment]
This should be fixed by PR #162.
