### ISSUE TITLE
[reducer] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdb in position 971: invalid continuation byte

### ISSUE THREAD

**Issue by pyoor** [MozillaSecurity/grizzly#163]
Triggered using the following command:
`python3 -m grizzly.replay --xvfb ~/builds/mc-debug/firefox ./ --strategy cssbeautify line --no-analysis`

Error:
```
[2020-09-02 11:26:06] Starting Grizzly Reducer
[2020-09-02 11:26:06] Ignoring: log-limit, timeout
[2020-09-02 11:26:06] Running with Xvfb
[2020-09-02 11:26:06] Using prefs included in testcase: '/tmp/grizzly/reduce/grzreducete8_7w0s/prefs.js'
[2020-09-02 11:26:06] Results will be stored in '/home/user/crashes/6cee2ad8_2020-08-24_08-03-15-0/results'
[2020-09-02 11:26:06] Exception during reduce
Traceback (most recent call last):
  File "/home/user/tools/grizzly/grizzly/reduce/reduce.py", line 1044, in run
    strategy.read_testcase(testcase_path)
  File "/home/user/tools/grizzly/grizzly/reduce/strategies.py", line 290, in read_testcase
    self.original_testcase = testcase_fp.read()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdb in position 971: invalid continuation byte
[2020-09-02 11:26:06] Reduction failed: QUAL_REDUCER_ERROR
[2020-09-02 11:26:06] Shutting down...
[2020-09-02 11:26:06] Leaving working files at '/tmp/grizzly/reduce/grzreducete8_7w0s' for inspection.
```

**Comment by tysmith** [comment]
Fixed by #168
