### ISSUE TITLE
Browser startup failure during reduction

### ISSUE THREAD

**Issue by pyoor** [MozillaSecurity/grizzly#171]
We should probably set a much higher relaunch count to handle potential browser startup errors as opposed to the count used during fuzzing.

```
[2020-10-28 08:01:54] FFPuppet LaunchError: Failure waiting for browser connection
[2020-10-28 08:01:55] Exception during reduce
Traceback (most recent call last):
  File "/home/user/tools/grizzly/grizzly/reduce/reduce.py", line 1041, in run
    result = reducer.run()
  File "/home/user/tools/lithium/src/lithium/reducer.py", line 1312, in run
    result = self.strategy.main(self.testcase, self.interesting, self.testcaseTempFilename)
  File "/home/user/tools/lithium/src/lithium/reducer.py", line 378, in main
    result, anySingle, testcase = self.run(testcase, interesting, tempFilename)  # pylint: disable=invalid-name
  File "/home/user/tools/lithium/src/lithium/reducer.py", line 454, in run
    if interesting(test_to_try):
  File "/home/user/tools/lithium/src/lithium/reducer.py", line 1469, in interesting
    inter = self.conditionScript.interesting(self.conditionArgs, tempPrefix)
  File "/home/user/tools/grizzly/grizzly/reduce/reduce.py", line 79, in interesting
    return self._job.lithium_interesting(temp_prefix)
  File "/home/user/tools/grizzly/grizzly/reduce/reduce.py", line 479, in lithium_interesting
    interesting_report = self._run(testcase, run_prefix)
  File "/home/user/tools/grizzly/grizzly/reduce/reduce.py", line 635, in _run
    runner.launch(location, env_mod=self._env_mod, max_retries=4, retry_delay=15)
  File "/home/user/tools/grizzly/grizzly/common/runner.py", line 107, in launch
    self._target.launch(location, env_mod=env_mod)
  File "/home/user/tools/grizzly/grizzly/target/puppet_target.py", line 222, in launch
    raise TargetLaunchError(str(exc), Report(log_path, self.binary)) from None
grizzly.target.target.TargetLaunchError: Failure waiting for browser connection
```

**Comment by tysmith** [comment]
Do you mean a longer launch timeout?
