### ISSUE TITLE
 Grizzly.reduce error : module 'lithium' has no attribute 'Minimize'

### ISSUE THREAD

**Issue by valentino004** [MozillaSecurity/grizzly#178]
Hello fuzzing team,

i got an error when running python3 -m grizzly.reduce -h
I update/upgrade my Ubuntu, remove/reinstall Grizzly but the error persist. 
thanks for help 

```
Traceback (most recent call last):
File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
return _get_module_details(pkg_main_name, error)
File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
import(pkg_name)
File "/home/user/code/grizzly/grizzly/reduce/init.py", line 27, in <module>
from .reduce import ReductionJob # noqa pylint: disable=wrong-import-position
File "/home/user/code/grizzly/grizzly/reduce/reduce.py", line 25, in <module>
from . import strategies as strategies_module, testcase_contents
File "/home/user/code/grizzly/grizzly/reduce/strategies.py", line 67, in <module>
class MinimizeLines(ReduceStage):
File "/home/user/code/grizzly/grizzly/reduce/strategies.py", line 69, in MinimizeLines
strategy_type = lithium.Minimize
AttributeError: module 'lithium' has no attribute 'Minimize'
```

-Yassine-

**Comment by jschwartzentruber** [comment]
Hi Yassine,

Can you check `pip list` to see what version of lithium you have installed? If you did `pip install lithium-reducer`, that will be broken as above, since the latest lithium version isn't compatible with grizzly. 

Please install grizzly with `pip install grizzly-framework[reduce]` and it will specify the correct lithium version.

**Comment by valentino004** [comment]
Problem resolved  :) 
Thanks a lot
