### ISSUE TITLE
Missing pyusb from setup.py

### ISSUE THREAD

**Issue by pyoor** [MozillaSecurity/grizzly#179]
When running grizzly.reduce:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/forb1dden/.local/lib/python3.8/site-packages/grizzly/__init__.py", line 2, in <module>
    import usb.core
ModuleNotFoundError: No module named 'usb'
```

**Comment by tysmith** [comment]
Did you pip install `grizzly-framework` (correct) or `grizzly` (incorrect)?

**Comment by pyoor** [comment]
Let's just silently close this issue and never mention it again.
