### ISSUE TITLE
Assertion failure in purge_optional()

### ISSUE THREAD

**Issue by tysmith** [MozillaSecurity/grizzly#258]
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/worker/grizzly-auto-run/grizzly/grizzly/__main__.py", line 12, in <module>
    raise SystemExit(main(GrizzlyArgs().parse_args()))
  File "/home/worker/grizzly-auto-run/grizzly/grizzly/main.py", line 137, in main
    session.run(
  File "/home/worker/grizzly-auto-run/grizzly/grizzly/session.py", line 242, in run
    current_test.purge_optional(result.served)
  File "/home/worker/grizzly-auto-run/grizzly/grizzly/common/storage.py", line 517, in purge_optional
    assert all(fname in opt_files for fname in keep_opt)
AssertionError
```

**Comment by tysmith** [comment]
Fixed by PR #259
