### ISSUE TITLE
[sapphire] ValueError: Invalid IPv6 URL

### ISSUE THREAD

**Issue by tysmith** [MozillaSecurity/grizzly#265]
```
Traceback (most recent call last):
  File "/home/worker/grizzly-auto-run/grizzly/sapphire/worker.py", line 120, in handle_request
    url = urlparse(unquote(raw_url.group("url").decode("ascii")))
  File "/usr/lib/python3.8/urllib/parse.py", line 373, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python3.8/urllib/parse.py", line 464, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```

**Comment by tysmith** [comment]
Fixed by cee9ce3
