### ISSUE TITLE
TypeError: 'NoneType' object is not iterable [@crashData]

### ISSUE THREAD

**Issue by posidron** [MozillaSecurity/grizzly#276]
Hey guys,

received this after a long steady run.

```
[2022-02-19 10:24:12] I5341-R15 
[2022-02-19 10:24:43] I5342-R15 
[2022-02-19 10:24:47] Shutting down...
[2022-02-19 10:24:47] Done.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/chdieh/.local/share/virtualenvs/edgeharness-pO-8rhhf/lib/python3.9/site-packages/grizzly/__main__.py", line 12, in <module>
    raise SystemExit(main(GrizzlyArgs().parse_args()))
  File "/Users/chdieh/.local/share/virtualenvs/edgeharness-pO-8rhhf/lib/python3.9/site-packages/grizzly/main.py", line 140, in main
    session.run(
  File "/Users/chdieh/.local/share/virtualenvs/edgeharness-pO-8rhhf/lib/python3.9/site-packages/grizzly/session.py", line 254, in run
    bucket_hash = report.crash_hash
  File "/Users/chdieh/.local/share/virtualenvs/edgeharness-pO-8rhhf/lib/python3.9/site-packages/grizzly/common/report.py", line 123, in crash_hash
    return self.calc_hash(self.crash_signature)
  File "/Users/chdieh/.local/share/virtualenvs/edgeharness-pO-8rhhf/lib/python3.9/site-packages/grizzly/common/report.py", line 191, in crash_signature
    self._signature = self.crash_info.createCrashSignature(
  File "/Users/chdieh/.local/share/virtualenvs/edgeharness-pO-8rhhf/lib/python3.9/site-packages/grizzly/common/report.py", line 163, in crash_info
    self._crash_info = CrashInfo.fromRawCrashData(
  File "/Users/chdieh/.local/share/virtualenvs/edgeharness-pO-8rhhf/lib/python3.9/site-packages/FTB/Signatures/CrashInfo.py", line 300, in fromRawCrashData
    result = AppleCrashInfo(stdout, stderr, configuration, auxCrashData)
  File "/Users/chdieh/.local/share/virtualenvs/edgeharness-pO-8rhhf/lib/python3.9/site-packages/FTB/Signatures/CrashInfo.py", line 1452, in __init__
    for line in crashData:
TypeError: 'NoneType' object is not iterable
```

**Comment by tysmith** [comment]
@posidron Any chance you have the logs from the browser? They would be in `/tmp/grizzly/logs/logs_<random>/`?

**Comment by posidron** [comment]
No such folder in `/tmp/`

**Comment by jschwartzentruber** [comment]
It should be in `$TMPDIR/grizzly`, not `/tmp` on macos.

**Comment by posidron** [comment]
I can not share the entire browser logs and I only see the usual `[ffpuppet] Reason. code: ALERT` in the last ones. However, I am not sure those are the ones which got left from that particular run. Will message if I see something else in those logs once it happens again.

**Comment by jschwartzentruber** [comment]
So `auxCrashData` must be `None` or we wouldn't get that exception. So does stderr contain `Mac OS X`? Is there actually a crash?
In any case, this should be fixed in https://github.com/MozillaSecurity/FuzzManager/pull/827.

**Comment by posidron** [comment]
No crash was logged before the crash in Grizzly happened. Depending on what you are referring to via Mac OS X, keep in mind they changed their id to "macOS". I could not see any traces of both strings.

**Comment by jschwartzentruber** [comment]
Fixed in https://pypi.org/project/FuzzManager/0.5.0/

I was asking about "Mac OS X" because if that string doesn't appear in either `auxCrashData` or `stderr`, FM won't try to parse it as `AppleCrashInfo` as seen in your traceback (see [CrashInfo.py](https://github.com/MozillaSecurity/FuzzManager/blob/06edf9dd6555417f60f6500ca4ec163198568687/FTB/Signatures/CrashInfo.py#L300)).
