### ISSUE TITLE
AttributeError: 'WindowsPath' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by KJ-Jordan** [MozillaSecurity/grizzly#280]
@posidron 

After noticing an upgrade to prefpicker that Grizzly uses the following is happening:

Traceback (most recent call last):
  File "python3\bin\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "python3\bin\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "python3\bin\lib\site-packages\grizzly\__main__.py", line 12, in <module>
    raise SystemExit(main(GrizzlyArgs().parse_args()))
  File "python3\bin\lib\site-packages\grizzly\main.py", line 94, in main
    target.process_assets()
  File "python3\bin\lib\site-packages\grizzly\target\puppet_target.py", line 318, in process_assets
    if template.endswith("browser-fuzzing.yml"):
@AttributeError: 'WindowsPath' object has no attribute 'endswith'

**Comment by tysmith** [comment]
@KJ-Jordan thanks for the report. This is a known issue and will be fixed shortly.

**Comment by tysmith** [comment]
Fixed by commit 19d96cf and release 0.14.1
