### ISSUE TITLE
Assertion failure when startup failure is detected and using `--any-crash`

### ISSUE THREAD

**Issue by tysmith** [MozillaSecurity/grizzly#282]
Found by @pyoor.
```
[2022-03-10 16:08:42] [lines] Removing chunk from 83 to 115 of 211
[2022-03-10 16:08:52] Empty request received from browser during bootstrap!
[2022-03-10 16:08:52] Running test, part 1/2 (1/1)...
[2022-03-10 16:08:53] Test case was not served
[2022-03-10 16:08:53] Delayed startup failure detected
[2022-03-10 16:08:53] Processing result...
[2022-03-10 16:08:53] Result: Different signature: [@ Init] (6b66dfb0:6e5cb68a)
[2022-03-10 16:08:53] Exception during reduction!
Traceback (most recent call last):
  File "/home/jkratzer/tools/grizzly/grizzly/reduce/[core.py](http://core.py/)", line 869, in main
    return_code = [mgr.run](http://mgr.run/)(repeat=args.repeat, min_results=args.min_crashes)
  File "/home/jkratzer/tools/grizzly/grizzly/reduce/[core.py](http://core.py/)", line 501, in run
    results = [replay.run](http://replay.run/)(
  File "/home/jkratzer/tools/grizzly/grizzly/replay/[replay.py](http://replay.py/)", line 464, in run
    assert all(x.expected for x in reports.values())
AssertionError
[2022-03-10 16:08:53] Shutting down...
[2022-03-10 16:08:53] Done.
```

This should properly handle unexpected results when a start up failure occurs.

**Comment by tysmith** [comment]
Fixed by PR #283.
