### ISSUE TITLE
Tox lint failures on fresh 22.04 install

### ISSUE THREAD

**Issue by tysmith** [MozillaSecurity/grizzly#344]
```
$ tox -e lint
lint: commands[0]> pre-commit run -a
[INFO] Installing environment for https://github.com/pycqa/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/user/.cache/pre-commit/repolv4lkg7s/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /home/user/.cache/pre-commit/repolv4lkg7s
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [14 lines of output]
          Traceback (most recent call last):
            File "/home/user/.cache/pre-commit/repolv4lkg7s/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
              main()
            File "/home/user/.cache/pre-commit/repolv4lkg7s/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
            File "/home/user/.cache/pre-commit/repolv4lkg7s/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
            File "/tmp/pip-build-env-zplk438v/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
            File "/tmp/pip-build-env-zplk438v/overlay/lib/python3.10/site-packages/poetry/core/factory.py", line 57, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
          
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
    
Check the log at /home/user/.cache/pre-commit/pre-commit.log
```

**Comment by tysmith** [comment]
Looks like it might be time to drop Python 3.7 support.

```
An unexpected error has occurred: CalledProcessError: command: ('/home/worker/.cache/pre-commit/repo7r3djlts/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /home/worker/.cache/pre-commit/repo7r3djlts
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'done'
    
stderr:
    ERROR: Package 'isort' requires a different Python: 3.7.16 not in '>=3.8.0'
    
Check the log at /home/worker/.cache/pre-commit/pre-commit.log
ERROR: InvocationError for command /tmp/decision-repo-3nwh99v2/.tox/lint/bin/pre-commit run -a (exited with code 3)
```
