### ISSUE TITLE
[status] sqlite3.OperationalError is hit when running lots of instances

### ISSUE THREAD

**Issue by tysmith** [MozillaSecurity/grizzly#62]
This was hit multiple times while running 24 instances of grizzly in parallel.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/worker/grizzly-auto-run/grizzly/grizzly/__main__.py", line 13, in <module>
    sys.exit(console_main())
  File "/home/worker/grizzly-auto-run/grizzly/grizzly/main.py", line 53, in console_main
    return main(GrizzlyArgs().parse_args())
  File "/home/worker/grizzly-auto-run/grizzly/grizzly/main.py", line 158, in main
    display_mode=display_mode)
  File "/home/worker/grizzly-auto-run/grizzly/grizzly/session.py", line 42, in __init__
    self.status = Status.start()
  File "/home/worker/grizzly-auto-run/grizzly/grizzly/common/status.py", line 193, in star
t
    time_stamp INTEGER DEFAULT 0);""")
sqlite3.OperationalError: database is locked
```

**Comment by tysmith** [comment]
Fixed by commit 4d64c82cbc8c7398f56128ea2b639f50e9d2a3cc
